// database.js
// ALGORITMO DE INTELIGENCIA DE PRERARACIÓN FÍSICA MARCIAL (V6 MAX 100)

const zenQuotes = [
  "El dolor de hoy es la fuerza de mañana.",
  "El hierro se afila con hierro, el espíritu con disciplina.",
  "No busques la victoria en el combate, búscala en tu voluntad.",
  "Caer mil veces, levantarse mil y una.",
  "La verdadera maestría es dominar el propio cuerpo antes que la mente del oponente.",
  "Como el bambú: flexible en la tormenta, irrompible en su raíz.",
  "La constancia es la espada que corta la montaña de la imposibilidad.",
  "Un guerrero no se rinde ante lo que le gusta, encuentra el gusto en lo que es difícil.",
  "El sudor es la tinta con la que escribes tu leyenda.",
  "Sé como el agua, mi amigo. Fluye o golpea.",
  "El obstáculo es el camino.",
  "No es lo que te sucede, sino cómo reaccionas lo que importa.",
  "La dificultad es el alimento de las almas valientes.",
  "Desde lo uno, conoce lo diez mil.",
  "El viaje de mil millas comienza con un solo paso.",
  "La suavidad vence a la dureza; la lentitud vence a la prisa.",
  "Mañana ganarás a quien eras hoy.",
  "Aquel que se domina a sí mismo es el dueño de su destino.",
  "La disciplina es el puente entre las metas y los logros.",
  "El espíritu debe estar siempre por encima de la técnica.",
  "Vacía tu mente, sé amorfo, moldeable como el agua.",
  "La mejor venganza es ser diferente a quien causó el daño.",
  "El éxito no es el final, el fracaso no es la ruina: es el valor para seguir lo que cuenta.",
  "Un momento de paciencia puede evitar un gran desastre.",
  "La mente es un excelente sirviente, pero un maestro terrible.",
  "Si no hay enemigo en tu interior, el enemigo externo no podrá dañarte.",
  "No ores por una vida fácil, ora por la fuerza para soportar una difícil.",
  "El guerrero exitoso es un hombre promedio con un enfoque similar al láser.",
  "La potencia definitiva grita menos pero rompe con gravedad cósmica.",
  "En el centro del caos reside la oportunidad.",
  "Conocerte a ti mismo es la única victoria real sobre la tierra.",
  "La voluntad de ganar no es nada sin la voluntad de prepararse.",
  "El reposo es el maestro del movimiento; el silencio el padre de la acción.",
  "Un verdadero filo mantiene su borde incluso en la masacre del agotamiento.",
  "La paciencia afila la cuchilla; la agresión ciega solo la agota.",
  "No te detengas cuando te canses, detente cuando hayas terminado.",
  "El único oponente real eres tú mismo hace un minuto.",
  "Excava el pozo antes de tener sed; forja el músculo antes del combate.",
  "La maestría no es un destino, es el sendero que caminas hoy.",
  "No pienses, siente. Es como un dedo apuntando a la luna.",
  "Acepta todo tal como es; la resistencia mental es debilidad.",
  "Haz cada cosa en tu entrenamiento como si fuera la última.",
  "Tu vida es lo que tus pensamientos construyen en el silencio del dojo.",
  "Lo que es difícil de soportar, es dulce de recordar al final del camino.",
  "La adversidad introduce a un hombre consigo mismo.",
  "El dojo no tiene paredes; entrena en cada respiración, en cada paso.",
  "Silencio en la mente, fuego en la técnica, titanio en la voluntad.",
  "Ningún árbol se vuelve robusto si no es azotado por el viento de la carga física."
];

// Base de Datos Estructural Híbrida - De Lvl 1 a Lvl 100
const EXERCISE_DB = [
  // --- FUERZA: EMPUJE ---
  { id: "str_1", n: "Empuje de Aprendiz", real: "Flexiones de Rodillas", s: "str", f: "push", lvl_min: 1, lvl_max: 10, t: "reps", domain: "conditioning", baseVal: 5, scale: 0.5, desc: "1. Apoya las rodillas en el suelo cruzando los tobillos detrás. 2. Coloca las manos al ancho de hombros, alineadas justo bajo el pecho con el núcleo apretado. 3. Desciende lentamente hasta que tu pecho roce el suelo, doblando los codos a 45 grados hacia atrás. 4. Empuja el suelo firmemente para volver arriba extendiendo los brazos. Consejo Zen: Evita arquear la zona lumbar, mantén tu espalda recta como una tabla.", m: "./img/techniques/webp/str_1.webp", alt: null, equip: "none", avoidInjuries: ["wrist"] },
  { id: "str_2", n: "Hierro Forjado", real: "Flexiones Clásicas", s: "str", f: "push", lvl_min: 5, lvl_max: 20, t: "reps", domain: "conditioning", baseVal: 8, scale: 0.8, desc: "1. Colócate en postura de plancha alta sobre la punta de tus pies y con las manos bajo tus hombros. 2. Contrae fuertemente los glúteos y el core. 3. Desciende de forma controlada llevando los codos a 45 grados de tu cuerpo hasta rozar el suelo con tu pecho. 4. Empuja de forma explosiva hasta bloquear los codos. Consejo Zen: No permitas que tu cadera caiga; la firmeza de tu centro es la base de tu fuerza.", m: "./img/techniques/webp/str_2.webp", alt: null, equip: "none", avoidInjuries: ["wrist"] },
  { id: "str_1_decline", n: "Empuje Inclinado Inverso", real: "Flexiones Declinadas", s: "str", f: "push", lvl_min: 8, lvl_max: 22, t: "reps", domain: "conditioning", baseVal: 8, scale: 0.6, desc: "1. Coloca tus pies elevados sobre un banco o silla estable y tus manos en el suelo bajo tus hombros. 2. Mantén el núcleo y glúteos compactos para evitar arquear la pelvis. 3. Baja controladamente el pecho hasta rozar la tierra. 4. Empuja con fuerza bloqueando los codos. Consejo Zen: Esta declinación traslada la fuerza al pectoral superior y los deltoides frontales de forma segura.", m: "./img/techniques/webp/str_1_decline.webp", alt: null, equip: "none", avoidInjuries: ["wrist"] },
  { id: "str_3", n: "Torre Angular", real: "Pike Pushups", s: "str", f: "push", lvl_min: 15, lvl_max: 35, t: "reps", domain: "conditioning", baseVal: 5, scale: 0.5, desc: "1. Eleva las caderas formando una 'V' invertida con pies y manos en el suelo. 2. Mira hacia tus pies para mantener el cuello neutro. 3. Flexiona los codos bajando tu cabeza diagonalmente hacia adelante de tus manos, formando un trípode. 4. Empuja el suelo en ángulo diagonal hasta estirar los brazos. Consejo Zen: Este ejercicio esculpe tus hombros; mantén las piernas rígidas and la cadera alta durante toda la serie.", m: "./img/techniques/webp/str_3.webp", alt: null, equip: "none", avoidInjuries: ["wrist", "shoulder"] },
  { id: "str_2_dips", n: "Suspensión del Tigre", real: "Fondos en Paralelas", s: "str", f: "push", lvl_min: 12, lvl_max: 32, t: "reps", domain: "conditioning", baseVal: 5, scale: 0.5, desc: "1. Suspéndete sobre unas barras paralelas con los brazos completamente bloqueados. 2. Inclina el torso levemente hacia el frente e inhala al descender doblando los codos hasta que tus hombros pasen por debajo del codo. 3. Empuja con violencia controlada hasta volver arriba bloqueando brazos. Consejo Zen: No dejes que tus hombros colapsen cerca de las orejas, deprime tus escápulas constantemente.", m: "./img/techniques/webp/str_2_dips.webp", alt: null, equip: "none", avoidInjuries: ["wrist", "shoulder"] },
  { id: "str_4", n: "Diamante Sólido", real: "Flexiones Diamante", s: "str", f: "push", lvl_min: 20, lvl_max: 40, t: "reps", domain: "conditioning", baseVal: 8, scale: 0.6, desc: "1. En postura de flexión, junta tus manos bajo el pecho uniendo tus dedos índices y pulgares formando la silueta de un diamante. 2. Manteniendo el cuerpo recto y rígido, desciende el pecho de forma controlada hasta rozar tus manos. 3. Empuja extendiendo los codos al 100%, enfocando toda la tensión en tus tríceps. Consejo Zen: Mantén los codos pegados a las costillas para proteger tus hombros y maximizar el estímulo.", m: "./img/techniques/webp/str_4.webp", alt: null, equip: "none", avoidInjuries: ["wrist"] },
  { id: "str_5", n: "Estallido de Dragón", real: "Flexiones Pliométricas", s: "str", f: "push", lvl_min: 30, lvl_max: 55, t: "reps", domain: "conditioning", baseVal: 5, scale: 0.5, desc: "1. Desde la postura de plancha clásica, desciende de forma controlada. 2. Empuja el suelo de forma violenta y explosiva, reclutando todas tus fibras rápidas para levantar tus manos de la tierra. 3. Da una palmada rápida en el aire si tienes el nivel y vuelve a colocar tus manos. 4. Absorbe el impacto flexionando los codos de forma elástica. Consejo Zen: Busca altura en el despegue, no velocidad de repetición.", m: "./img/techniques/webp/str_5.webp", alt: null, equip: "none", avoidInjuries: ["wrist"] },
  { id: "str_6", n: "Toque del Arquero", real: "Flexiones Arquero", s: "str", f: "push", lvl_min: 45, lvl_max: 70, t: "reps", domain: "conditioning", baseVal: 6, scale: 0.4, desc: "1. Coloca las manos en el suelo en un agarre muy ancho, con los dedos apuntando hacia afuera. 2. Desciende hacia un lado doblando ese codo mientras mantienes el brazo contrario completamente recto. 3. Empuja de vuelta al centro y repite en el lado opuesto. Consejo Zen: Siente el estiramiento en tu pectoral del brazo estirado y la fuerza unilateral masiva en el brazo flexionado.", m: "./img/techniques/webp/str_6.webp", alt: null, equip: "none", avoidInjuries: ["wrist", "shoulder"] },
  { id: "str_7", n: "Titán Invertido", real: "Wall Handstand Pushups", s: "str", f: "push", lvl_min: 60, lvl_max: 85, t: "reps", domain: "conditioning", baseVal: 3, scale: 0.3, desc: "1. Haz una parada de manos apoyado contra la pared, manteniendo tu cuerpo alinedo. 2. Flexiona los codos descendiendo la corona de tu cabeza lentamente de forma controlada hasta rozar el suelo. 3. Empuja firmemente contra la pared y el suelo hasta estirar tus codos por completo. Consejo Zen: Ejercicio supremo para hombros de piedra. Contrae el core para no curvar en exceso la columna.", m: "./img/techniques/webp/str_7.webp", alt: null, equip: "none", avoidInjuries: ["wrist", "shoulder"] },
  { id: "str_8", n: "Monje de una Mano", real: "Flexión a Una Mano", s: "str", f: "push", lvl_min: 75, lvl_max: 100, t: "reps", domain: "conditioning", baseVal: 3, scale: 0.2, desc: "1. Coloca una mano firme en el suelo en línea con tu esternón y los pies muy abiertos detrás para soporte. 2. Apoya tu otra mano detrás de tu espalda lumbar. 3. Desciende lentamente manteniendo tu torso paralelo al suelo. 4. Empuja el suelo luchando contra la rotación lateral del cuerpo. Consejo Zen: El control absoluto del núcleo y oblicuos es más importante que la fuerza del empuje.", m: "./img/techniques/webp/str_8.webp", alt: null, equip: "none", avoidInjuries: ["wrist", "shoulder"] },

  // --- FUERZA: TRACCIÓN ---
  { id: "str_9", n: "Raíces Sumergidas", real: "Remo Invertido Básico", s: "str", f: "pull", lvl_min: 1, lvl_max: 15, t: "reps", domain: "conditioning", baseVal: 8, scale: 0.8, desc: "1. Colócate debajo de una mesa resistente o barra baja. 2. Sujétate del borde con las palmas mirando hacia tus pies (agarre prono). 3. Mantén el cuerpo tenso y recto de talones a cabeza. 4. Tira de tu pecho hacia el borde retrayendo tus escápulas y llevando tus hombros hacia atrás. 5. Desciende lento. Consejo Zen: No dejes caer tu cadera, mantén glúteos activos.", m: "./img/techniques/webp/str_9.webp", alt: null, equip: "none", avoidInjuries: [] },
  { id: "str_9_1", n: "Alineación Escapular", real: "Retracciones Escapulares Boca Abajo", s: "str", f: "pull", lvl_min: 1, lvl_max: 10, t: "reps", domain: "conditioning", baseVal: 12, scale: 0.5, desc: "1. Tumbado boca abajo en el suelo con la frente apoyada para alinear las cervicales. 2. Coloca tus brazos a los lados flexionados formando una 'W'. 3. Levanta las manos y codos del suelo apretando fuertemente tus omóplatos en el centro de tu espalda. 4. Sostén 2 segundos arriba en contracción isométrica máxima y baja. Consejo Zen: Ejercicio vital de reeducación postural para forjar dorsales y trapecio.", m: "./img/techniques/webp/str_9_1.webp", alt: null, equip: "none", avoidInjuries: [] },
  { id: "str_9_2", n: "Deslizamiento del Dojo", real: "Dominadas Deslizantes en Suelo", s: "str", f: "pull", lvl_min: 5, lvl_max: 20, t: "reps", domain: "conditioning", baseVal: 8, scale: 0.6, desc: "1. Acuéstate boca abajo en un suelo liso (puedes usar calcetines o una toalla bajo el torso). 2. Coloca las palmas de las manos firmes en el suelo delante de ti al ancho de hombros. 3. Ejerce presión hacia abajo y arrastra tu propio cuerpo hacia adelante deslizando el abdomen por el suelo, imitando el patrón de una dominada estricta. 4. Empújate hacia atrás con control. Consejo Zen: Mantén los hombros deprimidos.", m: "./img/techniques/webp/str_9_2.webp", alt: null, equip: "none", avoidInjuries: [] },
  { id: "str_9_3", n: "Senda del Arquero Deslizante", real: "Remo Deslizante Unilateral", s: "str", f: "pull", lvl_min: 15, lvl_max: 35, t: "reps", domain: "conditioning", baseVal: 6, scale: 0.4, desc: "1. En la misma posición boca abajo deslizante. 2. Alterna la tracción tirando fuertemente con un solo brazo al costado mientras mantienes el otro extendido para estabilizar el arrastre asimétrico. 3. Regresa y alterna. Consejo Zen: Excelente ejercicio para corregir desbalances de fuerza entre tus dorsales.", m: "./img/techniques/webp/str_9_3.webp", alt: null, equip: "none", avoidInjuries: [] },
  { id: "str_10_chin", n: "Tracción Inversa Guerrera", real: "Dominadas Supinas (Chin-ups)", s: "str", f: "pull", lvl_min: 12, lvl_max: 35, t: "reps", domain: "conditioning", baseVal: 4, scale: 0.4, desc: "1. Sujétate de la barra con un agarre supino (las palmas mirando hacia tu rostro) a la anchura de tus hombros. 2. Saca el pecho y tracciona llevando los codos con fuerza hacia tus costillas. 3. Sube estrictamente hasta que tu barbilla sobrepase la barra. 4. Baja controlando la fase excéntrica. Consejo Zen: El agarre supino recluta más intensamente tus bíceps y dorsales inferiores, sirviendo de transición ideal hacia la dominada prona estricta.", m: "./img/techniques/webp/str_10_chin.webp", alt: null, equip: "bar", avoidInjuries: ["shoulder"] },
  { id: "str_11", n: "Tracción del Tigre", real: "Dominadas Estrictas", s: "str", f: "pull", lvl_min: 20, lvl_max: 50, t: "reps", domain: "conditioning", baseVal: 5, scale: 0.4, desc: "1. Cuélgate libremente de la barra con agarre prono. 2. Contrae tu core para evitar balanceos. 3. Inicia la tracción tirando de tus codos hacia tus costillas y saca el pecho, subiendo verticalmente hasta que tu barbilla supere completamente la barra. 4. Desciende con control. Consejo Zen: Evita dar patadas o impulsos de cadera; la pureza de la técnica forja al guerrero.", m: "./img/techniques/webp/str_11.webp", alt: null, equip: "bar", avoidInjuries: ["shoulder"] },
  { id: "str_11_1", n: "Ascenso Explosivo", real: "Dominadas Explosivas al Esternón", s: "str", f: "pull", lvl_min: 35, lvl_max: 60, t: "reps", domain: "conditioning", baseVal: 4, scale: 0.3, desc: "1. Ejecuta una dominada con la máxima velocidad y aceleración posibles. 2. Tira de la barra hacia abajo buscando que el impacto se realice a la altura de tu pecho o esternón en vez de tu barbilla. 3. Desciende con control elástico. Consejo Zen: La explosividad desarrolla la potencia necesaria para pasar de tracción a empuje en el Muscle Up.", m: "./img/techniques/webp/str_11_1.webp", alt: null, equip: "bar", avoidInjuries: ["shoulder", "wrist"] },
  { id: "str_11_2", n: "Fuerza en Barra Recta", real: "Fondos sobre Barra Recta", s: "str", f: "pull", lvl_min: 30, lvl_max: 55, t: "reps", domain: "conditioning", baseVal: 6, scale: 0.4, desc: "1. Colócate apoyado sobre la barra recta con tus brazos bloqueados y apóyate firmemente sobre ella. 2. Flexiona tus codos inclinando ligeramente tu torso hacia adelante, bajando el pecho hasta tocar la barra con control. 3. Empuja hacia arriba con fuerza hasta estirar los brazos. Consejo Zen: Ejercicio indispensable para desarrollar la fase final de empuje de tus transiciones en barra.", m: "./img/techniques/webp/str_11_2.webp", alt: null, equip: "bar", avoidInjuries: ["shoulder", "wrist"] },
  { id: "str_11_3", n: "Transición Impulsada", real: "Muscle-Up Asistido con Salto", s: "str", f: "pull", lvl_min: 45, lvl_max: 65, t: "reps", domain: "conditioning", baseVal: 3, scale: 0.2, desc: "1. Colócate bajo una barra baja donde tus pies toquen cómodamente el suelo. 2. Da un pequeño salto coordinado que asista tu fase de tracción. 3. Rota tus muñecas rápidamente sobre la barra al sobrepasarla para quedar apoyado arriba en fondo de barra recta. Consejo Zen: Práctica neuromuscular clave para internalizar el movimiento de transición sin lastimarte.", m: "./img/techniques/webp/str_11_3.webp", alt: null, equip: "bar", avoidInjuries: ["shoulder", "wrist"] },
  { id: "str_12", n: "Tigre Enfurecido", real: "L-Sit Pull-ups", s: "str", f: "pull", lvl_min: 40, lvl_max: 70, t: "reps", domain: "conditioning", baseVal: 4, scale: 0.3, desc: "1. Cuélgate de la barra y eleva tus piernas rígidas a 90 grados formando una perfecta 'L'. 2. Manteniendo tus piernas inmóviles y paralelas al suelo, ejecuta dominadas estrictas llevando tu barbilla sobre la barra. 3. Desciende con control. Consejo Zen: Este ejercicio ejerce una gran demanda de compresión abdominal y activa el dorsal de forma aislada.", m: "./img/techniques/webp/str_12.webp", alt: null, equip: "bar", avoidInjuries: ["shoulder", "back"] },
  { id: "str_13", n: "Muro Traspasado", real: "Muscle-Ups Lentos", s: "str", f: "pull", lvl_min: 60, lvl_max: 85, t: "reps", domain: "conditioning", baseVal: 2, scale: 0.2, desc: "1. Cuélgate con un agarre falso (muñecas descansando sobre la barra). 2. Tracciona explosivamente llevando la barra al esternón. 3. Rota los hombros de forma agresiva y rápida hacia adelante en la transición. 4. Empuja en fondo de barra recta hasta bloquear brazos. Consejo Zen: El ejercicio rey de unificación muscular en calistenia; requiere tanto tracción como empuje impecables.", m: "./img/techniques/webp/str_13.webp", alt: null, equip: "bar", avoidInjuries: ["shoulder", "wrist"] },
  { id: "str_14", n: "Voluntad de Dioses", real: "Dominada Uno Brazo (OAP)", s: "str", f: "pull", lvl_min: 80, lvl_max: 100, t: "reps", domain: "conditioning", baseVal: 1, scale: 0.1, desc: "1. Cuélgate de la barra con un solo brazo utilizando un agarre de hierro. 2. Aprieta tu núcleo abdominal y mantén el otro brazo pegado al costado de tu cuerpo. 3. Tracciona estrictamente y de forma vertical hasta que tu barbilla supere completamente tu mano de agarre. Consejo Zen: Nivel supremo de calistenia y fuerza de tracción unilateral absoluta.", m: "./img/techniques/webp/str_14.webp", alt: null, equip: "bar", avoidInjuries: ["shoulder", "wrist"] },
 
  // --- FUERZA: PIERNAS ---
  { id: "str_15", n: "Paso Fundamental", real: "Sentadillas Libres", s: "str", f: "legs", lvl_min: 1, lvl_max: 15, t: "reps", domain: "conditioning", baseVal: 15, scale: 1.0, desc: "1. Abre tus pies al ancho de hombros con las puntas apuntando ligeramente hacia afuera. 2. Mantén el pecho erguido y desciende la cadera empujando los glúteos atrás, rompiendo la línea paralela de las rodillas (90 grados). 3. Empuja con fuerza con los talones para volver a la posición de pie. Consejo Zen: Alinea tus rodillas con las puntas de tus pies en todo momento para proteger tus meniscos.", m: "./img/techniques/webp/str_15.webp", alt: null, equip: "none", avoidInjuries: [] },
  { id: "str_16", n: "Zancada Guerrera", real: "Split Squat Estricto", s: "str", f: "legs", lvl_min: 3, lvl_max: 25, t: "reps", domain: "conditioning", baseVal: 12, scale: 0.8, desc: "1. Colócate de pie y da un paso largo hacia adelante. 2. Manteniendo el torso erguido como una lanza, desciende de forma completamente vertical hasta que tu rodilla trasera casi roce el suelo. 3. Empuja de vuelta con tu pierna delantera manteniendo el equilibrio. Consejo Zen: Excelente ejercicio unilateral para corregir desbalances musculares y estabilizar la pelvis.", m: "./img/techniques/webp/str_16.webp", alt: null, equip: "none", avoidInjuries: ["knee"] },
  { id: "str_15_cossack", n: "Paso de Jinete Cosaco", real: "Sentadillas Cosacas", s: "str", f: "legs", lvl_min: 8, lvl_max: 30, t: "reps", domain: "conditioning", baseVal: 10, scale: 0.6, desc: "1. Adopta una postura muy ancha con los pies. 2. Transfiere tu peso corporal hacia un lado descendiendo la cadera en sentadilla profunda sobre esa pierna, mientras mantienes la pierna opuesta totalmente estirada con el talón apoyado y la punta al cielo. 3. Vuelve al centro empujando el talón y alterna. Consejo Zen: Desarrolla fuerza unilateral masiva y la flexibilidad activa lateral indispensable para golpear con patadas altas.", m: null, alt: null, equip: "none", avoidInjuries: ["knee"] },
  { id: "str_17", n: "Gravedad Dividida", real: "Sentadilla Búlgara", s: "str", f: "legs", lvl_min: 8, lvl_max: 45, t: "reps", domain: "conditioning", baseVal: 10, scale: 0.6, desc: "1. Coloca el empeine de un pie apoyado detrás de ti sobre un banco o soporte a la altura de tu rodilla. 2. Da un paso al frente con la otra pierna. 3. Desciende con control el muslo delantero hasta que rompa el paralelo horizontal. 4. Empuja fuertemente con el talón delantero para volver arriba. Consejo Zen: Ejercicio constructor de potencia y masa muscular en cuádriceps y glúteos.", m: null, alt: null, equip: "none", avoidInjuries: ["knee"] },
  { id: "str_16_pistol_asist", n: "Pilar Asistido", real: "Pistol Squat Asistida", s: "str", f: "legs", lvl_min: 20, lvl_max: 45, t: "reps", domain: "conditioning", baseVal: 6, scale: 0.4, desc: "1. Colócate frente al marco de una puerta o estructura vertical y sujétate suavemente con una o dos manos. 2. Levanta una pierna y desciende sobre la pierna contraria de forma profunda. 3. Utiliza la ayuda de tus manos para guiar la subida y controlar el equilibrio. Consejo Zen: Paso intermedio crucial para internalizar la mecánica de la sentadilla a una sola pierna sin lesionar tus rodillas.", m: null, alt: null, equip: "none", avoidInjuries: ["knee"] },
  { id: "str_18", n: "Flecha de Rodilla", real: "Sissy Squats", s: "str", f: "legs", lvl_min: 35, lvl_max: 65, t: "reps", domain: "conditioning", baseVal: 8, scale: 0.5, desc: "1. Sujétate de una estructura stable con una mano. 2. Elévate sobre la punta de tus pies y, doblando tus rodillas, empújalas hacia adelante mientras dejas caer tu torso recto hacia atrás formando una línea oblicua. 3. Siente el estiramiento y contracción masiva en tus cuádriceps y empuja de vuelta. Consejo Zen: Fortalece tendones y cartílagos rotulianos de forma increíble.", m: null, alt: null, equip: "none", avoidInjuries: ["knee"] },
  { id: "str_19", n: "Pilar Inferior", real: "Pistol Squat Puro", s: "str", f: "legs", lvl_min: 50, lvl_max: 85, t: "reps", domain: "conditioning", baseVal: 4, scale: 0.3, desc: "1. Colócate de pie sobre una pierna y extiende la otra pierna completamente recta hacia adelante. 2. Manteniendo el equilibrio y el core tenso, desciende la cadera hasta que tu isquiotibial bese tu talón. 3. Empuja con fuerza con el talón de base para levantarte. Consejo Zen: Requiere una gran dosis de movilidad de tobillo y fuerza en tus flexores de cadera.", m: null, alt: null, equip: "none", avoidInjuries: ["knee"] },
  { id: "str_20", n: "Dragón Oculto", real: "Dragon Pistols", s: "str", f: "legs", lvl_min: 70, lvl_max: 100, t: "reps", domain: "conditioning", baseVal: 3, scale: 0.2, desc: "1. Colócate sobre una pierna y cruza la pierna libre por detrás de la rodilla de soporte. 2. Desciende de forma profunda manteniendo el pie trasero flotando en el aire sin tocar el suelo. 3. Empuja verticalmente de vuelta al inicio. Consejo Zen: Ejercicio legendario que prueba tu destreza, equilibrio asimétrico y tendones inquebrantables.", m: null, alt: null, equip: "none", avoidInjuries: ["knee"] },

  // --- VELOCIDAD / CARDIO Y CRAWLS (ANIMALES) ---
  { id: "spd_1", n: "Sombra Guerrera", real: "Boxeo de Sombra (Lento/Técnico)", s: "spd", f: "cardio", lvl_min: 1, lvl_max: 20, t: "time", domain: "conditioning", baseVal: 45, scale: 1.5, desc: "1. Adopta guardia marcial relajada. 2. Muévete de forma constante por tu espacio puliendo golpes fundamentales (jab, cruzado, gancho) coordinados con esquivas. 3. Respira de forma regular. Consejo Zen: No busques golpear fuerte, enfócate en la fluidez del movimiento y en coordinar pies con manos.", m: null, alt: null, equip: "none", avoidInjuries: [] },
  { id: "spd_2", n: "Viento Cruzado", real: "Mountain Climbers", s: "spd", f: "cardio", lvl_min: 3, lvl_max: 35, t: "time", domain: "conditioning", baseVal: 30, scale: 1.5, desc: "1. Adopta postura de plancha alta con los brazos rectos y manos firmes. 2. Lleva una rodilla hacia tu pecho de forma explosiva manteniendo la otra extendida. 3. Alterna a alta velocidad imitando el trote en la montaña sin elevar la cadera en el aire. Consejo Zen: Mantén el core apretado para estabilizar tus lumbares.", m: null, alt: null, equip: "none", avoidInjuries: ["wrist"] },
  { id: "spd_2_slip", n: "Esquivas de Combate", real: "Desplazamientos y Esquivas de Boxeo (Slip & Roll Agility)", s: "spd", f: "cardio", lvl_min: 5, lvl_max: 25, t: "time", domain: "conditioning", baseVal: 30, scale: 1.0, desc: "1. Adopta guardia de combate con manos protegiendo el mentón. 2. Realiza flexiones laterales de tronco e inclinaciones (slips) esquivando golpes imaginarios. 3. Pasa por debajo de un golpe imaginario doblando las rodillas en U (roll) y recupera la guardia. Consejo Zen: No quites la vista del frente y mantén el peso centrado.", m: null, alt: null, equip: "none", avoidInjuries: [] },
  { id: "spd_3", n: "Sendero del Oso", real: "Bear Crawls Lentos", s: "spd", f: "cardio", lvl_min: 5, lvl_max: 40, t: "time", domain: "conditioning", baseVal: 35, scale: 1.0, desc: "1. En cuadrupedia con pies y manos apoyados. 2. Eleva tus rodillas justo 5 centímetros del suelo manteniendo la espalda plana como una mesa. 3. Avanza silenciosamente moviendo brazo y pie contrarios de forma coordinada. Consejo Zen: No dejes que tus rodillas suban ni tu espalda se encorve; esto lubrica hombros y fortalece el core.", m: null, alt: null, equip: "none", avoidInjuries: ["wrist"] },
  { id: "spd_4", n: "Defensa Cíclica", real: "Crab Walks", s: "spd", f: "cardio", lvl_min: 8, lvl_max: 50, t: "time", domain: "conditioning", baseVal: 30, scale: 1.2, desc: "1. Siéntate y coloca las manos detrás de ti en el suelo. Elevación inversa. 2. Levanta la pelvis del suelo cargando peso en tus manos y talones. 3. Avanza hacia atrás o adelante imitando el andar del cangrejo de forma fluida. Consejo Zen: Excelente ejercicio de apertura para tus hombros delanteros y fortalecimiento de muñecas.", m: null, alt: null, equip: "none", avoidInjuries: ["wrist", "shoulder"] },
  { id: "spd_4_kicks", n: "Patadas de Sombra", real: "Patadas de Sombra Continuas (Shadow Kicks)", s: "spd", f: "cardio", lvl_min: 15, lvl_max: 40, t: "time", domain: "conditioning", baseVal: 40, scale: 1.2, desc: "1. En guardia de combate activa. 2. Ejecuta patadas frontales, circulares y laterales alternando las piernas con control. 3. Enfócate en recuperar la guardia inmediatamente después de cada impacto. Consejo Zen: Prioriza la técnica y la altura progresiva sobre la velocidad para evitar distensiones.", m: null, alt: null, equip: "none", avoidInjuries: ["knee"] },
  { id: "spd_5", n: "Defensa Mortal", real: "Burpees Marciales", s: "spd", f: "cardio", lvl_min: 30, lvl_max: 65, t: "reps", domain: "conditioning", baseVal: 10, scale: 0.8, desc: "1. Desde la postura de pie, desciende y apoya las manos. 2. Lanza las piernas atrás cayendo de pecho al suelo en una flexión elástica. 3. Recupera la postura agrupando los pies de golpe y ejecuta un salto explosivo al aire aplaudiendo sobre la cabeza. Consejo Zen: Unificador metabólico supremo que prueba tu resistencia marcial.", m: null, alt: null, equip: "none", avoidInjuries: ["wrist", "knee"] },
  { id: "spd_6", n: "Patada Evasiva", real: "Sit Throughs / Grappler Drills", s: "spd", f: "cardio", lvl_min: 40, lvl_max: 75, t: "reps", domain: "conditioning", baseVal: 14, scale: 0.8, desc: "1. Desde la posición de cuadrupedia de oso (rodillas elevadas). 2. Rota el cuerpo levantando la mano derecha y pateando con tu pierna izquierda hacia tu costado derecho rozando el suelo. 3. Vuelve al centro y repite en el sentido opuesto. Consejo Zen: Movimiento dinámico de lucha que esculpe tus oblicuos y core lateral al 100%.", m: null, alt: null, equip: "none", avoidInjuries: ["wrist"] },
  { id: "spd_7", n: "Acecho Cocodrilo", real: "Spiderman Walks Flotantes", s: "spd", f: "cardio", lvl_min: 55, lvl_max: 85, t: "time", domain: "conditioning", baseVal: 30, scale: 1.0, desc: "1. Adopta postura de plancha baja rozando el suelo con el pecho. 2. Avanza llevando tu rodilla derecha hacia tu codo derecho por fuera de tu cuerpo mientras tu brazo izquierdo avanza al frente. 3. Alterna a baja altura. Consejo Zen: El verdadero infierno metabólico e isométrico de empuje.", m: null, alt: null, equip: "none", avoidInjuries: ["wrist", "shoulder", "knee"] },
  { id: "spd_8", n: "Salto del Guepardo", real: "Tuck Jumps Continuos", s: "spd", f: "cardio", lvl_min: 65, lvl_max: 90, t: "time", domain: "conditioning", baseVal: 20, scale: 1.5, desc: "1. De pie, flexiona levemente las rodillas. 2. Ejecuta un salto vertical con la máxima potencia posible, agrupando tus rodillas violentamente hacia tu pecho en el aire. 3. Cae amortiguando el impacto con la punta de los pies and encadena el siguiente salto. Consejo Zen: Máxima potencia pliométrica de piernas.", m: null, alt: null, equip: "none", avoidInjuries: ["knee"] },
  { id: "spd_9", n: "Asalto Fantasma", real: "Burpees Monopodales (1 Pierna)", s: "spd", f: "cardio", lvl_min: 80, lvl_max: 100, t: "reps", domain: "conditioning", baseVal: 8, scale: 0.5, desc: "1. Colócate sobre un solo pie, manteniendo el otro flotando en el aire. 2. Desciende y realiza una flexión asimétrica completa a una pierna. 3. Vuelve a agrupar el pie y ejecuta un salto explosivo con la pierna de base sin apoyar la otra. Consejo Zen: Exige un nivel extremo de estabilidad articular en tobillos y fuerza unilateral.", m: null, alt: null, equip: "none", avoidInjuries: ["wrist", "knee"] },

  // --- ENDURANCE: CORE DINÁMICO & ISOMÉTRICO GENERAL ---
  { id: "end_1", n: "Centro Pasivo", real: "Plancha Apoyando Rodillas", s: "end", f: "core", lvl_min: 1, lvl_max: 10, t: "time", domain: "conditioning", baseVal: 30, scale: 2.0, desc: "1. Colócate sobre los codos en el suelo y apoya las rodillas detrás. 2. Contrae fuertemente los glúteos induciendo una retroversión pélvica para aplanar tu espalda baja. 3. Sostén la postura respirando con calma. Consejo Zen: Aprende a conectar tu mente con tu pared abdominal desde el inicio.", m: null, alt: null, equip: "none", avoidInjuries: [] },
  { id: "end_1_bridge", n: "Puente de Glúteos", real: "Puente de Glúteos Dinámico", s: "end", f: "core", lvl_min: 1, lvl_max: 15, t: "reps", domain: "conditioning", baseVal: 12, scale: 0.8, desc: "1. Acuéstate boca arriba con las rodillas dobladas y los pies planos en el suelo al ancho de hombros. 2. Empuja con fuerza los talones para levantar las caderas del suelo, apretando los glúteos al máximo arriba. 3. Mantén una línea recta desde las rodillas hasta los hombros. 4. Baja lento. Consejo Zen: No hiperextiendas la espalda baja, la fuerza debe nacer de los glúteos e isquiotibiales.", m: null, alt: null, equip: "none", avoidInjuries: [] },
  { id: "end_2", n: "Fortaleza Viva", real: "Plancha Clásica Estricta", s: "end", f: "core", lvl_min: 2, lvl_max: 25, t: "time", domain: "conditioning", baseVal: 40, scale: 1.5, desc: "1. Apoya los antebrazos en el suelo al ancho de hombros y elévate sobre tus pies. 2. Contrae tus cuádriceps, glúteos e infla el espacio entre tus hombros (depresión escapular). 3. Hunde el abdomen hacia tu columna y respira de forma regular. Consejo Zen: La plancha perfecta es activa, no pasiva; mantén tensión total en tu línea de fuerza.", m: null, alt: null, equip: "none", avoidInjuries: [] },
  { id: "end_2_side", n: "Plancha Lateral Activa", real: "Plancha Lateral con Elevación", s: "end", f: "core", lvl_min: 5, lvl_max: 25, t: "time", domain: "conditioning", baseVal: 30, scale: 1.0, desc: "1. Apóyate sobre un antebrazo y el lateral del pie correspondiente, manteniendo el cuerpo alineado de pies a cabeza. 2. Eleva la cadera del suelo para formar una línea diagonal rígida. 3. Sostén el brazo libre apuntando al cielo o sobre la cadera. Consejo Zen: Activa fuertemente los oblicuos del lado de apoyo para evitar que la cadera descienda.", m: null, alt: null, equip: "none", avoidInjuries: ["shoulder"] },
  { id: "end_3", n: "Core de Hierro", real: "Hollow Body Hold", s: "end", f: "core", lvl_min: 15, lvl_max: 40, t: "time", domain: "conditioning", baseVal: 30, scale: 1.2, desc: "1. Acuéstate boca arriba. 2. Levanta tus hombros y escápulas de la tierra y extiende tus piernas juntas flotando en el aire. 3. Presiona tu zona lumbar fuertemente contra el suelo, sin dejar espacios. Consejo Zen: Si tu espalda baja se despega o arquea levemente, dobla un poco las rodillas hacia tu pecho para aliviar.", m: null, alt: null, equip: "none", avoidInjuries: ["back"] },
  { id: "end_4", n: "Paso Pantano", real: "Elevación Piernas", s: "end", f: "core", lvl_min: 10, lvl_max: 50, t: "reps", domain: "conditioning", baseVal: 15, scale: 0.5, desc: "1. Acuéstate sobre tu espalda en el suelo colocando las manos planas a los lados. 2. Manteniendo tus rodillas bloqueadas y piernas estiradas, elévalas de forma controlada hasta formar un ángulo de 90 grados. 3. Desciende lentamente casi rozando la tierra con tus talones. Consejo Zen: No uses impulso, enfoca la fuerza en tus abdominales inferiores.", m: null, alt: null, equip: "none", avoidInjuries: ["back"] },
  { id: "end_4_1", n: "Compresión Abortada", real: "Tuck L-Sit en Suelo / Paraletas", s: "end", f: "core", lvl_min: 15, lvl_max: 55, t: "time", domain: "conditioning", baseVal: 15, scale: 0.5, desc: "1. Siéntate con el torso erguido, rodillas flexionadas cerca del pecho y manos apoyadas a los costados de tus muslos. 2. Empuja el suelo estirando los codos hasta suspender tu cadera del suelo. 3. Agrupa tus rodillas hacia tu torso despegando tus pies de la tierra. Sostén. Consejo Zen: La base isométrica primordial del L-Sit.", m: null, alt: null, equip: "none", avoidInjuries: ["wrist", "back"] },
  { id: "end_4_2", n: "Compresión Asimétrica", real: "L-Sit Unilateral (Pierna Extendida)", s: "end", f: "core", lvl_min: 25, lvl_max: 70, t: "time", domain: "conditioning", baseVal: 15, scale: 0.6, desc: "1. Colócate en postura de apoyo elevado (suelo o paralelas). 2. Empuja para suspender tus caderas. 3. Extiende una pierna completamente recta y paralela al suelo mientras mantienes la otra rodilla doblada hacia el pecho. 4. Alterna tus piernas a mitad de tiempo. Consejo Zen: Excelente ejercicio para acostumbrar a tus flexores y cuádriceps al L-Sit completo.", m: null, alt: null, equip: "none", avoidInjuries: ["wrist", "back"] },
  { id: "end_5", n: "Defensa Bivalva", real: "V-Ups Abdominales", s: "end", f: "core", lvl_min: 40, lvl_max: 65, t: "reps", domain: "conditioning", baseVal: 10, scale: 0.4, desc: "1. Acostado boca arriba con brazos estirados detrás de tu cabeza. 2. Eleva simultáneamente tu torso y piernas rectas, buscando formar una perfecta 'V' y tocar tus pies con las manos en el punto más alto del aire. 3. Desciende con control. Consejo Zen: Sincroniza la elevación de ambas partes del cuerpo de forma elástica.", m: null, alt: null, equip: "none", avoidInjuries: ["back"] },
  { id: "end_6", n: "Bandera Dragón", real: "Dragon Flags (Bruce Lee Style)", s: "end", f: "core", lvl_min: 60, lvl_max: 85, t: "reps", domain: "conditioning", baseVal: 4, scale: 0.3, desc: "1. Acostado boca arriba, sujétate fuertemente de una barra o soporte sólido detrás de tu cabeza. 2. Contrae todo tu cuerpo y levántalo completo apoyándote solo en tus hombros y trapecio superior. 3. Desciende lentamente todo tu cuerpo recto como una aguja casi a tocar el banco, y vuelve a subir. Consejo Zen: El máximo templo de fuerza isométrica abdominal de Bruce Lee.", m: null, alt: null, equip: "bar", avoidInjuries: ["back"] },
  { id: "end_7", n: "Levitación Core", real: "L / V-Sit Suelo", s: "end", f: "core", lvl_min: 80, lvl_max: 100, t: "time", domain: "conditioning", baseVal: 10, scale: 0.8, desc: "1. Coloca las manos firmes a los lados de tus muslos en el suelo. 2. Empuja contra la tierra bloqueando tus codos y elevando tus glúteos del piso de forma deprimida. 3. Eleva ambas piernas completamente rectas y paralelas al suelo. Sostén respirando. Consejo Zen: Combina compresión extrema del core y flexibilidad activa de isquiotibiales.", m: null, alt: null, equip: "none", avoidInjuries: ["wrist", "back"] },

  // --- ENDURANCE: CUELLO & CADENA POSTERIOR (Lucha) ---
  { id: "end_8", n: "Pétalo Dorado", real: "Superman Hold", s: "end", f: "neck", lvl_min: 1, lvl_max: 30, t: "time", domain: "conditioning", baseVal: 30, scale: 1.5, desc: "1. Acuéstate boca abajo con brazos y piernas estirados. 2. Contrae glúteos e isquiotibiales elevando pecho, brazos y pies simultáneamente del suelo. 3. Sostén la postura mirando al frente. Consejo Zen: Ejercicio indispensable de cadena posterior para contrarrestar la fatiga del core anterior.", m: null, alt: null, equip: "none", avoidInjuries: [] },
  { id: "end_9", n: "Puente Lucha Básico", real: "Wrestler Static Bridge Libre", s: "end", f: "neck", lvl_min: 30, lvl_max: 65, t: "time", domain: "conditioning", baseVal: 20, scale: 1.0, desc: "1. Acuéstate boca arriba y coloca tus pies cerca de tus glúteos. 2. Eleva tu cadera apoyando el peso en tus pies y en la coronilla de tu cabeza. 3. Usa tus manos en el suelo si no posees suficiente fuerza para aligerar la tensión. Consejo Zen: Fortalece las cervicales para prevenir impactos y mejorar la postura marcial.", m: null, alt: null, equip: "none", avoidInjuries: ["back"] },
  { id: "end_10", n: "Puente Combate Oscilado", real: "Dynamic Wrestler Bridge Rolls", s: "end", f: "neck", lvl_min: 60, lvl_max: 100, t: "reps", domain: "conditioning", baseVal: 10, scale: 0.5, desc: "1. En postura de puente de luchador. 2. Rueda lentamente el peso sobre tu cabeza, balanceándote de frente a coronilla controladamente. 3. Siente el estiramiento y fuerza muscular de tu cuello. Consejo Zen: Solo para maestros avanzados; este movimiento acondiciona la flexibilidad cervical extrema.", m: null, alt: null, equip: "none", avoidInjuries: ["back"] },

  // --- ENDURANCE: ISÓMETRICOS PIERNAS (Ma Bu) ---
  { id: "end_11", n: "Enraizamiento Base", real: "Ma Bu Alta (Kiba Dachi Cúspide)", s: "end", f: "iso_legs", lvl_min: 1, lvl_max: 30, t: "time", domain: "conditioning", baseVal: 40, scale: 1.5, desc: "1. Abre tus pies el doble de tu ancho de hombros con las puntas apuntando al frente. 2. Realiza un descenso leve a media sentadilla. 3. Coloca tus brazos extendidos al frente y sostén respirando. Consejo Zen: Postura marcial de enraizamiento básico que fortalece tus rodillas y cuádriceps de forma segura y firme.", m: null, alt: null, equip: "none", avoidInjuries: ["knee"] },
  { id: "end_12", n: "Muralla Inquebrantable", real: "Wall Sit", s: "end", f: "iso_legs", lvl_min: 20, lvl_max: 60, t: "time", domain: "conditioning", baseVal: 45, scale: 1.5, desc: "1. Apoya tu espalda firmemente contra una pared. 2. Desciende las caderas hasta que tus muslos queden exactamente horizontales (90 grados). 3. Mantén tus pies firmes a la distancia de tus caderas y las manos en tus costados (sin apoyarlas en tus piernas). Consejo Zen: Bloquea tu mente para tolerar la quemazón del ácido láctico.", m: null, alt: null, equip: "none", avoidInjuries: ["knee"] },
  { id: "end_13", n: "Roble del Sensei", real: "Ma Bu Profundo (Shaolin Stance)", s: "end", f: "iso_legs", lvl_min: 50, lvl_max: 100, t: "time", domain: "conditioning", baseVal: 40, scale: 1.0, desc: "1. Abre tus pies ampliamente de forma abierta. 2. Desciende la cadera de forma profunda rompiendo el paralelo horizontal de tus muslos con la espalda erguida. 3. Junta tus palmas en el pecho. Consejo Zen: Cientos de años de templamiento mental marcial shaolin se ocultan en la dureza de sostener esta postura solitaria.", m: null, alt: null, equip: "none", avoidInjuries: ["knee"] },

  // --- FLEXIBILIDAD UPPER ---
  { id: "flex_1", n: "Corriente de Agua", real: "Gato / Camello Pélvico", s: "flex", f: "upper", lvl_min: 1, lvl_max: 30, t: "reps", domain: "mobility", baseVal: 15, scale: 0.5, desc: "1. En cuadrupedia sobre el suelo. 2. Arquea tu columna hacia abajo levantando la mirada e inspirando profundo (Gato). 3. Exhala empujando el suelo y encorvando tu espalda hacia el cielo (Camello). Consejo Zen: Articula vértebra por vértebra de forma extremadamente pausada para oxigenar tus discos cervicales.", m: null, alt: null, equip: "none", avoidInjuries: [] },
  { id: "flex_1_downdog", n: "Perro Boca Abajo", real: "Perro Boca Abajo (Downward Dog)", s: "flex", f: "upper", lvl_min: 5, lvl_max: 30, t: "time", domain: "mobility", baseVal: 35, scale: 1.0, desc: "1. Comienza en cuadrupedia, apoya los dedos de los pies y eleva la pelvis empujando los glúteos al cielo. 2. Estira los brazos y las piernas para formar una 'V' invertida. 3. Presiona los talones hacia el suelo y relaja la cabeza entre los hombros. Consejo Zen: Empuja el suelo activamente con las manos para alargar tu columna vertebral.", m: null, alt: null, equip: "none", avoidInjuries: ["wrist", "shoulder"] },
  { id: "flex_2", n: "Ennebrado Espiral", real: "Torsión Thread The Needle", s: "flex", f: "upper", lvl_min: 15, lvl_max: 50, t: "time", domain: "mobility", baseVal: 40, scale: 1.0, desc: "1. En cuadrupedia. 2. Pasa un brazo por debajo de tu pecho deslizándolo de forma transversal hasta apoyar tu hombro y oreja en el suelo. 3. Siente la torsión en tu columna torácica. 4. Extiende el otro brazo hacia adelante. Consejo Zen: Descomprime tu espalda alta disipando la tensión acumulada.", m: null, alt: null, equip: "none", avoidInjuries: [] },
  { id: "flex_3", n: "Punzón Veneno", real: "Escorpión Abierto Supino", s: "flex", f: "upper", lvl_min: 30, lvl_max: 70, t: "time", domain: "mobility", baseVal: 35, scale: 1.0, desc: "1. Acuéstate boca abajo con tus brazos extendidos a los costados formando una cruz. 2. Levanta la pierna derecha y cruza el pie por detrás buscando tocar el suelo de tu costado izquierdo con tu punta. 3. Mantén el pectoral contrario firme en la tierra. Consejo Zen: Fantástica combinación de apertura de pectoral y torsión lumbar profunda.", m: null, alt: null, equip: "none", avoidInjuries: ["back"] },
  { id: "flex_4", n: "Hojas Guillotina", real: "Dislocaciones Completas Palo/Toalla", s: "flex", f: "upper", lvl_min: 50, lvl_max: 100, t: "reps", domain: "mobility", baseVal: 15, scale: 0.3, desc: "1. Sujeta un palo de escoba o toalla tensa con un agarre muy ancho al frente. 2. Manteniendo tus codos bloqueados por completo, levanta tus brazos y pásalos de forma continua por encima de tu cabeza hacia tu espalda lumbar. 3. Regresa al frente de la misma forma. Consejo Zen: Lubrica tus manguitos rotadores previniendo desgarros y lesiones escapulares.", m: null, alt: null, equip: "none", avoidInjuries: ["shoulder"] },

  // --- FLEXIBILIDAD LOWER ---
  { id: "flex_5", n: "Cauce Blando", real: "Plegado Asistido Frente Libre", s: "flex", f: "lower", lvl_min: 1, lvl_max: 30, t: "time", domain: "mobility", baseVal: 45, scale: 1.0, desc: "1. Siéntate con las piernas abiertas al frente de forma extendida. 2. Exhala e inclina tu torso hacia adelante desde tu cadera, extendiendo tus brazos a tocar tus pies o espinillas. 3. Relaja la respiración bajando con cada exhalación de forma suave y sin rebotar. Consejo Zen: Relaja tu fascia posterior profunda y estira tus isquiotibiales con paciencia marcial.", m: null, alt: null, equip: "none", avoidInjuries: [] },
  { id: "flex_5_butterfly", n: "Mariposa Marcial", real: "Estiramiento de Mariposa (Butterfly Stretch)", s: "flex", f: "lower", lvl_min: 1, lvl_max: 25, t: "time", domain: "mobility", baseVal: 40, scale: 1.0, desc: "1. Siéntate en el suelo con la espalda erguida, junta las plantas de los pies y acércalas a tu pelvis. 2. Sujeta tus pies con las manos y empuja suavemente las rodillas hacia el suelo utilizando los codos. 3. Mantén el pecho alzado y respira hondo. Consejo Zen: No balancees las piernas bruscamente; permite que la gravedad y la exhalación abran tu cadera.", m: null, alt: null, equip: "none", avoidInjuries: [] },
  { id: "flex_6", n: "Reposo Cauteloso", real: "Zancada Psoas Pasivo Lunge", s: "flex", f: "lower", lvl_min: 10, lvl_max: 40, t: "time", domain: "mobility", baseVal: 40, scale: 1.0, desc: "1. Da una zancada profunda colocando tu rodilla trasera apoyada en el suelo. 2. Empuja tus caderas suavemente hacia el frente, sintiendo el estiramiento profundo en el flexor de la cadera (psoas) trasero. 3. Mantén el torso erguido. Consejo Zen: Este estiramiento alivia la tensión de la espalda baja provocada por pasar mucho tiempo sentado.", m: null, alt: null, equip: "none", avoidInjuries: [] },
  { id: "flex_7", n: "Rana en Estanque", real: "Frog Pose", s: "flex", f: "lower", lvl_min: 25, lvl_max: 60, t: "time", domain: "mobility", baseVal: 40, scale: 1.0, desc: "1. Colócate sobre rodillas apoyadas y ábrelas transversalmente lo más que puedas en un suelo acolchado. 2. Flexiona tus tobillos y alinea rodillas con pies formando ángulos de 90 grados. 3. Apoya antebrazos al frente y empuja tu pelvis con control hacia atrás. Consejo Zen: Abre tus aductores profundos con suavidad liberando tensión en tu articulación pélvica.", m: null, alt: null, equip: "none", avoidInjuries: [] },
  { id: "flex_8", n: "Sauce en el Río", real: "Pike Stretch V-Sit", s: "flex", f: "lower", lvl_min: 40, lvl_max: 75, t: "time", domain: "mobility", baseVal: 40, scale: 1.0, desc: "1. Siéntate con las piernas abiertas al máximo al frente de forma extendida. 2. Manteniendo las rodillas bloqueadas, inclina tu torso de forma plana al frente buscando rozar tu abdomen contra el suelo. 3. Sostén respirando de forma pausada y suave. Consejo Zen: Desarrolla la flexibilidad de tus isquiotibiales asimétrica necesaria para las patadas altas marciales.", m: null, alt: null, equip: "none", avoidInjuries: [] },
  { id: "flex_9", n: "Espada Tijera Front", real: "Spagat Frontal", s: "flex", f: "lower", lvl_min: 60, lvl_max: 90, t: "time", domain: "mobility", baseVal: 35, scale: 1.0, desc: "1. Desliza una pierna estirada al frente y la otra pierna recta hacia atrás de forma paralela. 2. Desciende la cadera controladamente manteniendo tu torso alineado al centro. 3. Usa soportes o tus manos a los lados para regular el peso corporal. Consejo Zen: Estiramiento legendario que forja tendones de acrílico y abre tus caderas.", m: null, alt: null, equip: "none", avoidInjuries: ["knee"] },
  { id: "flex_10", n: "Abanico Sol", real: "Spagat Lateral Middle Split Max", s: "flex", f: "lower", lvl_min: 80, lvl_max: 100, t: "time", domain: "mobility", baseVal: 30, scale: 1.0, desc: "1. Abre tus piernas hacia los costados de forma completamente transversal. 2. Desciende con control apoyándote en tus antebrazos, buscando alinear tus talones con tu cadera hasta que tu pubis roce la tierra. 3. Sostén respirando profundamente. Consejo Zen: El rey absoluto de la flexibilidad marcial; forja articulaciones blindadas.", m: null, alt: null, equip: "none", avoidInjuries: ["knee"] }
];
